# Generated by Django 5.2.1 on 2025-05-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('POSTER', 'Poster'), ('SEEKER', 'Seeker')], default='SEEKER'),
        ),
    ]
