# Generated by Django 5.2.1 on 2025-05-22 14:07

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('location', models.CharField(choices=[('MUMBAI', 'Mumbai'), ('DELHI', 'Delhi'), ('BENGALURU', 'Bengaluru'), ('HYDERABAD', 'Hyderabad'), ('CHENNAI', 'Chennai'), ('KOLKATA', 'Kolkata'), ('PUNE', 'Pune'), ('AHMEDABAD', 'Ahmedabad'), ('JAIPUR', 'Jaipur'), ('CHANDIGARH', 'Chandigarh'), ('KOCHI', 'Kochi'), ('BHUBANESWAR', 'Bhubaneswar'), ('INDORE', 'Indore'), ('LUCKNOW', 'Lucknow'), ('VISAKHAPATNAM', 'Visakhapatnam')], default='BENGALURU', max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=3)),
                ('category', models.CharField(choices=[('SOFTWARE_ENGINEERING', 'Software Engineering'), ('DATA_SCIENCE', 'Data Science'), ('CYBERSECURITY', 'Cybersecurity'), ('CLOUD_ENGINEERING', 'Cloud Engineering'), ('DEVOPS', 'DevOps'), ('AI_ML', 'AI & ML'), ('UI_UX_DESIGN', 'UI/UX Design'), ('IT_SUPPORT', 'IT Support'), ('NETWORK_ENGINEERING', 'Network Engineering'), ('DATABASE_ADMIN', 'Database Administration')], default='SOFTWARE_ENGINEERING', max_length=100)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance'), ('INTERN', 'Internship')], default='FULL_TIME', max_length=100)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry Level'), ('MID', 'Mid Level'), ('SENIOR', 'Senior Level'), ('LEAD', 'Lead'), ('EXEC', 'Executive')], default='MID', max_length=30)),
                ('mode', models.CharField(choices=[('REMOTE', 'Remote'), ('HIBRID', 'Hibrid'), ('WORK FROM OFFICE', 'Work From Office')], default='WORK FROM OFFICE', max_length=100)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='jobs_job_created_77460a_idx'), models.Index(fields=['is_active'], name='jobs_job_is_acti_b6ae73_idx')],
            },
        ),
    ]
