# Generated by Django 5.2.1 on 2025-05-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='MicroSoft', max_length=150),
        ),
    ]
